/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSlaRouteImport } from './routes/admin/sla'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWorkOrdersOverviewRouteImport } from './routes/admin/work-orders-overview'
import { Route as AdminContractorsIndexRouteImport } from './routes/admin/contractors/index'
import { Route as AdminContractorsIdRouteImport } from './routes/admin/contractors/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSlaRoute = AdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkOrdersOverviewRoute = AdminWorkOrdersOverviewRouteImport.update({
  id: '/work-orders-overview',
  path: '/work-orders-overview',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractorsIndexRoute = AdminContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractorsIdRoute = AdminContractorsIdRouteImport.update({
  id: '/contractors/$id',
  path: '/contractors/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors': typeof AdminContractorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sla': {
      id: '/admin/sla'
      path: '/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AdminSlaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/work-orders-overview': {
      id: '/admin/work-orders-overview'
      path: '/work-orders-overview'
      fullPath: '/admin/work-orders-overview'
      preLoaderRoute: typeof AdminWorkOrdersOverviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contractors/': {
      id: '/admin/contractors/'
      path: '/contractors'
      fullPath: '/admin/contractors/'
      preLoaderRoute: typeof AdminContractorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contractors/$id': {
      id: '/admin/contractors/$id'
      path: '/contractors/$id'
      fullPath: '/admin/contractors/$id'
      preLoaderRoute: typeof AdminContractorsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlaRoute: typeof AdminSlaRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkOrdersOverviewRoute: typeof AdminWorkOrdersOverviewRoute
  AdminContractorsIdRoute: typeof AdminContractorsIdRoute
  AdminContractorsIndexRoute: typeof AdminContractorsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlaRoute: AdminSlaRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkOrdersOverviewRoute: AdminWorkOrdersOverviewRoute,
  AdminContractorsIdRoute: AdminContractorsIdRoute,
  AdminContractorsIndexRoute: AdminContractorsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
