/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAiOversightRouteImport } from './routes/admin/ai-oversight'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGamificationRouteImport } from './routes/admin/gamification'
import { Route as AdminGlobalComplaintsRouteImport } from './routes/admin/global-complaints'
import { Route as AdminInteroperabilityRouteImport } from './routes/admin/interoperability'
import { Route as AdminMdmRouteImport } from './routes/admin/mdm'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSlaRouteImport } from './routes/admin/sla'
import { Route as AdminTrustSafetyRouteImport } from './routes/admin/trust-safety'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWorkOrdersOverviewRouteImport } from './routes/admin/work-orders-overview'
import { Route as AdminContractorsIndexRouteImport } from './routes/admin/contractors/index'
import { Route as AdminContractorsIdRouteImport } from './routes/admin/contractors/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiOversightRoute = AdminAiOversightRouteImport.update({
  id: '/ai-oversight',
  path: '/ai-oversight',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamificationRoute = AdminGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGlobalComplaintsRoute = AdminGlobalComplaintsRouteImport.update({
  id: '/global-complaints',
  path: '/global-complaints',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInteroperabilityRoute = AdminInteroperabilityRouteImport.update({
  id: '/interoperability',
  path: '/interoperability',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMdmRoute = AdminMdmRouteImport.update({
  id: '/mdm',
  path: '/mdm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSlaRoute = AdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTrustSafetyRoute = AdminTrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkOrdersOverviewRoute = AdminWorkOrdersOverviewRouteImport.update({
  id: '/work-orders-overview',
  path: '/work-orders-overview',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractorsIndexRoute = AdminContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractorsIdRoute = AdminContractorsIdRouteImport.update({
  id: '/contractors/$id',
  path: '/contractors/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/ai-oversight': typeof AdminAiOversightRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/global-complaints': typeof AdminGlobalComplaintsRoute
  '/admin/interoperability': typeof AdminInteroperabilityRoute
  '/admin/mdm': typeof AdminMdmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/trust-safety': typeof AdminTrustSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/ai-oversight': typeof AdminAiOversightRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/global-complaints': typeof AdminGlobalComplaintsRoute
  '/admin/interoperability': typeof AdminInteroperabilityRoute
  '/admin/mdm': typeof AdminMdmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/trust-safety': typeof AdminTrustSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors': typeof AdminContractorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/ai-oversight': typeof AdminAiOversightRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/global-complaints': typeof AdminGlobalComplaintsRoute
  '/admin/interoperability': typeof AdminInteroperabilityRoute
  '/admin/mdm': typeof AdminMdmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/trust-safety': typeof AdminTrustSafetyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/work-orders-overview': typeof AdminWorkOrdersOverviewRoute
  '/admin/contractors/$id': typeof AdminContractorsIdRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/admin/ai-oversight'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/gamification'
    | '/admin/global-complaints'
    | '/admin/interoperability'
    | '/admin/mdm'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/trust-safety'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/admin/ai-oversight'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/gamification'
    | '/admin/global-complaints'
    | '/admin/interoperability'
    | '/admin/mdm'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/trust-safety'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/admin/ai-oversight'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/gamification'
    | '/admin/global-complaints'
    | '/admin/interoperability'
    | '/admin/mdm'
    | '/admin/settings'
    | '/admin/sla'
    | '/admin/trust-safety'
    | '/admin/users'
    | '/admin/work-orders-overview'
    | '/admin/contractors/$id'
    | '/admin/contractors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-oversight': {
      id: '/admin/ai-oversight'
      path: '/ai-oversight'
      fullPath: '/admin/ai-oversight'
      preLoaderRoute: typeof AdminAiOversightRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gamification': {
      id: '/admin/gamification'
      path: '/gamification'
      fullPath: '/admin/gamification'
      preLoaderRoute: typeof AdminGamificationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/global-complaints': {
      id: '/admin/global-complaints'
      path: '/global-complaints'
      fullPath: '/admin/global-complaints'
      preLoaderRoute: typeof AdminGlobalComplaintsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/interoperability': {
      id: '/admin/interoperability'
      path: '/interoperability'
      fullPath: '/admin/interoperability'
      preLoaderRoute: typeof AdminInteroperabilityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mdm': {
      id: '/admin/mdm'
      path: '/mdm'
      fullPath: '/admin/mdm'
      preLoaderRoute: typeof AdminMdmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sla': {
      id: '/admin/sla'
      path: '/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AdminSlaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trust-safety': {
      id: '/admin/trust-safety'
      path: '/trust-safety'
      fullPath: '/admin/trust-safety'
      preLoaderRoute: typeof AdminTrustSafetyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/work-orders-overview': {
      id: '/admin/work-orders-overview'
      path: '/work-orders-overview'
      fullPath: '/admin/work-orders-overview'
      preLoaderRoute: typeof AdminWorkOrdersOverviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contractors/': {
      id: '/admin/contractors/'
      path: '/contractors'
      fullPath: '/admin/contractors/'
      preLoaderRoute: typeof AdminContractorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contractors/$id': {
      id: '/admin/contractors/$id'
      path: '/contractors/$id'
      fullPath: '/admin/contractors/$id'
      preLoaderRoute: typeof AdminContractorsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAiOversightRoute: typeof AdminAiOversightRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGamificationRoute: typeof AdminGamificationRoute
  AdminGlobalComplaintsRoute: typeof AdminGlobalComplaintsRoute
  AdminInteroperabilityRoute: typeof AdminInteroperabilityRoute
  AdminMdmRoute: typeof AdminMdmRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlaRoute: typeof AdminSlaRoute
  AdminTrustSafetyRoute: typeof AdminTrustSafetyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkOrdersOverviewRoute: typeof AdminWorkOrdersOverviewRoute
  AdminContractorsIdRoute: typeof AdminContractorsIdRoute
  AdminContractorsIndexRoute: typeof AdminContractorsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiOversightRoute: AdminAiOversightRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGamificationRoute: AdminGamificationRoute,
  AdminGlobalComplaintsRoute: AdminGlobalComplaintsRoute,
  AdminInteroperabilityRoute: AdminInteroperabilityRoute,
  AdminMdmRoute: AdminMdmRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlaRoute: AdminSlaRoute,
  AdminTrustSafetyRoute: AdminTrustSafetyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkOrdersOverviewRoute: AdminWorkOrdersOverviewRoute,
  AdminContractorsIdRoute: AdminContractorsIdRoute,
  AdminContractorsIndexRoute: AdminContractorsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
