/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthAdministrationRouteImport } from './routes/_auth/administration'
import { Route as AuthAiTriageRouteImport } from './routes/_auth/ai-triage'
import { Route as AuthAlertsRouteImport } from './routes/_auth/alerts'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthWorkPackagesRouteImport } from './routes/_auth/work-packages'
import { Route as MunicipalityAnalyticsRouteImport } from './routes/municipality/analytics'
import { Route as MunicipalityCitizenFeedbackRouteImport } from './routes/municipality/citizen-feedback'
import { Route as MunicipalityContractorInvoicesRouteImport } from './routes/municipality/contractor-invoices'
import { Route as MunicipalitySlaBreachRouteImport } from './routes/municipality/sla-breach'
import { Route as AuthAreasIndexRouteImport } from './routes/_auth/areas/index'
import { Route as AuthCivicIssuesIndexRouteImport } from './routes/_auth/civic-issues/index'
import { Route as AuthCivicIssuesIdRouteImport } from './routes/_auth/civic-issues/$id'
import { Route as AuthComplaintsIndexRouteImport } from './routes/_auth/complaints/index'
import { Route as AuthComplaintsIdRouteImport } from './routes/_auth/complaints/$id'
import { Route as AuthDepartmentsIndexRouteImport } from './routes/_auth/departments/index'
import { Route as AuthDepartmentsIdRouteImport } from './routes/_auth/departments/$id'
import { Route as AuthIssuesIndexRouteImport } from './routes/_auth/issues/index'
import { Route as AuthIssuesIdRouteImport } from './routes/_auth/issues/$id'
import { Route as AuthTendersIndexRouteImport } from './routes/_auth/tenders/index'
import { Route as AuthTendersIdRouteImport } from './routes/_auth/tenders/$id'
import { Route as AuthTendersNewRouteImport } from './routes/_auth/tenders/new'
import { Route as AuthWorkOrdersIndexRouteImport } from './routes/_auth/work-orders/index'
import { Route as AuthWorkOrdersIdRouteImport } from './routes/_auth/work-orders/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdministrationRoute = AuthAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAiTriageRoute = AuthAiTriageRouteImport.update({
  id: '/ai-triage',
  path: '/ai-triage',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlertsRoute = AuthAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkPackagesRoute = AuthWorkPackagesRouteImport.update({
  id: '/work-packages',
  path: '/work-packages',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MunicipalityAnalyticsRoute = MunicipalityAnalyticsRouteImport.update({
  id: '/municipality/analytics',
  path: '/municipality/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalityCitizenFeedbackRoute =
  MunicipalityCitizenFeedbackRouteImport.update({
    id: '/municipality/citizen-feedback',
    path: '/municipality/citizen-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const MunicipalityContractorInvoicesRoute =
  MunicipalityContractorInvoicesRouteImport.update({
    id: '/municipality/contractor-invoices',
    path: '/municipality/contractor-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const MunicipalitySlaBreachRoute = MunicipalitySlaBreachRouteImport.update({
  id: '/municipality/sla-breach',
  path: '/municipality/sla-breach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAreasIndexRoute = AuthAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCivicIssuesIndexRoute = AuthCivicIssuesIndexRouteImport.update({
  id: '/civic-issues/',
  path: '/civic-issues/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCivicIssuesIdRoute = AuthCivicIssuesIdRouteImport.update({
  id: '/civic-issues/$id',
  path: '/civic-issues/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthComplaintsIndexRoute = AuthComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthComplaintsIdRoute = AuthComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDepartmentsIndexRoute = AuthDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDepartmentsIdRoute = AuthDepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIssuesIndexRoute = AuthIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIssuesIdRoute = AuthIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTendersIndexRoute = AuthTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTendersIdRoute = AuthTendersIdRouteImport.update({
  id: '/tenders/$id',
  path: '/tenders/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTendersNewRoute = AuthTendersNewRouteImport.update({
  id: '/tenders/new',
  path: '/tenders/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkOrdersIndexRoute = AuthWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkOrdersIdRoute = AuthWorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthAdministrationRoute
  '/ai-triage': typeof AuthAiTriageRoute
  '/alerts': typeof AuthAlertsRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/map': typeof AuthMapRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/work-packages': typeof AuthWorkPackagesRoute
  '/municipality/analytics': typeof MunicipalityAnalyticsRoute
  '/municipality/citizen-feedback': typeof MunicipalityCitizenFeedbackRoute
  '/municipality/contractor-invoices': typeof MunicipalityContractorInvoicesRoute
  '/municipality/sla-breach': typeof MunicipalitySlaBreachRoute
  '/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/complaints/$id': typeof AuthComplaintsIdRoute
  '/departments/$id': typeof AuthDepartmentsIdRoute
  '/issues/$id': typeof AuthIssuesIdRoute
  '/tenders/$id': typeof AuthTendersIdRoute
  '/tenders/new': typeof AuthTendersNewRoute
  '/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/areas/': typeof AuthAreasIndexRoute
  '/civic-issues/': typeof AuthCivicIssuesIndexRoute
  '/complaints/': typeof AuthComplaintsIndexRoute
  '/departments/': typeof AuthDepartmentsIndexRoute
  '/issues/': typeof AuthIssuesIndexRoute
  '/tenders/': typeof AuthTendersIndexRoute
  '/work-orders/': typeof AuthWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthAdministrationRoute
  '/ai-triage': typeof AuthAiTriageRoute
  '/alerts': typeof AuthAlertsRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/map': typeof AuthMapRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/work-packages': typeof AuthWorkPackagesRoute
  '/municipality/analytics': typeof MunicipalityAnalyticsRoute
  '/municipality/citizen-feedback': typeof MunicipalityCitizenFeedbackRoute
  '/municipality/contractor-invoices': typeof MunicipalityContractorInvoicesRoute
  '/municipality/sla-breach': typeof MunicipalitySlaBreachRoute
  '/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/complaints/$id': typeof AuthComplaintsIdRoute
  '/departments/$id': typeof AuthDepartmentsIdRoute
  '/issues/$id': typeof AuthIssuesIdRoute
  '/tenders/$id': typeof AuthTendersIdRoute
  '/tenders/new': typeof AuthTendersNewRoute
  '/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/areas': typeof AuthAreasIndexRoute
  '/civic-issues': typeof AuthCivicIssuesIndexRoute
  '/complaints': typeof AuthComplaintsIndexRoute
  '/departments': typeof AuthDepartmentsIndexRoute
  '/issues': typeof AuthIssuesIndexRoute
  '/tenders': typeof AuthTendersIndexRoute
  '/work-orders': typeof AuthWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_auth/administration': typeof AuthAdministrationRoute
  '/_auth/ai-triage': typeof AuthAiTriageRoute
  '/_auth/alerts': typeof AuthAlertsRoute
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/work-packages': typeof AuthWorkPackagesRoute
  '/municipality/analytics': typeof MunicipalityAnalyticsRoute
  '/municipality/citizen-feedback': typeof MunicipalityCitizenFeedbackRoute
  '/municipality/contractor-invoices': typeof MunicipalityContractorInvoicesRoute
  '/municipality/sla-breach': typeof MunicipalitySlaBreachRoute
  '/_auth/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/_auth/complaints/$id': typeof AuthComplaintsIdRoute
  '/_auth/departments/$id': typeof AuthDepartmentsIdRoute
  '/_auth/issues/$id': typeof AuthIssuesIdRoute
  '/_auth/tenders/$id': typeof AuthTendersIdRoute
  '/_auth/tenders/new': typeof AuthTendersNewRoute
  '/_auth/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/_auth/areas/': typeof AuthAreasIndexRoute
  '/_auth/civic-issues/': typeof AuthCivicIssuesIndexRoute
  '/_auth/complaints/': typeof AuthComplaintsIndexRoute
  '/_auth/departments/': typeof AuthDepartmentsIndexRoute
  '/_auth/issues/': typeof AuthIssuesIndexRoute
  '/_auth/tenders/': typeof AuthTendersIndexRoute
  '/_auth/work-orders/': typeof AuthWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/administration'
    | '/ai-triage'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/settings'
    | '/work-packages'
    | '/municipality/analytics'
    | '/municipality/citizen-feedback'
    | '/municipality/contractor-invoices'
    | '/municipality/sla-breach'
    | '/civic-issues/$id'
    | '/complaints/$id'
    | '/departments/$id'
    | '/issues/$id'
    | '/tenders/$id'
    | '/tenders/new'
    | '/work-orders/$id'
    | '/areas/'
    | '/civic-issues/'
    | '/complaints/'
    | '/departments/'
    | '/issues/'
    | '/tenders/'
    | '/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/administration'
    | '/ai-triage'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/settings'
    | '/work-packages'
    | '/municipality/analytics'
    | '/municipality/citizen-feedback'
    | '/municipality/contractor-invoices'
    | '/municipality/sla-breach'
    | '/civic-issues/$id'
    | '/complaints/$id'
    | '/departments/$id'
    | '/issues/$id'
    | '/tenders/$id'
    | '/tenders/new'
    | '/work-orders/$id'
    | '/areas'
    | '/civic-issues'
    | '/complaints'
    | '/departments'
    | '/issues'
    | '/tenders'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/_auth/administration'
    | '/_auth/ai-triage'
    | '/_auth/alerts'
    | '/_auth/analytics'
    | '/_auth/dashboard'
    | '/_auth/map'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/work-packages'
    | '/municipality/analytics'
    | '/municipality/citizen-feedback'
    | '/municipality/contractor-invoices'
    | '/municipality/sla-breach'
    | '/_auth/civic-issues/$id'
    | '/_auth/complaints/$id'
    | '/_auth/departments/$id'
    | '/_auth/issues/$id'
    | '/_auth/tenders/$id'
    | '/_auth/tenders/new'
    | '/_auth/work-orders/$id'
    | '/_auth/areas/'
    | '/_auth/civic-issues/'
    | '/_auth/complaints/'
    | '/_auth/departments/'
    | '/_auth/issues/'
    | '/_auth/tenders/'
    | '/_auth/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MunicipalityAnalyticsRoute: typeof MunicipalityAnalyticsRoute
  MunicipalityCitizenFeedbackRoute: typeof MunicipalityCitizenFeedbackRoute
  MunicipalityContractorInvoicesRoute: typeof MunicipalityContractorInvoicesRoute
  MunicipalitySlaBreachRoute: typeof MunicipalitySlaBreachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/administration': {
      id: '/_auth/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthAdministrationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ai-triage': {
      id: '/_auth/ai-triage'
      path: '/ai-triage'
      fullPath: '/ai-triage'
      preLoaderRoute: typeof AuthAiTriageRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/alerts': {
      id: '/_auth/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthAlertsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-packages': {
      id: '/_auth/work-packages'
      path: '/work-packages'
      fullPath: '/work-packages'
      preLoaderRoute: typeof AuthWorkPackagesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/municipality/analytics': {
      id: '/municipality/analytics'
      path: '/municipality/analytics'
      fullPath: '/municipality/analytics'
      preLoaderRoute: typeof MunicipalityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipality/citizen-feedback': {
      id: '/municipality/citizen-feedback'
      path: '/municipality/citizen-feedback'
      fullPath: '/municipality/citizen-feedback'
      preLoaderRoute: typeof MunicipalityCitizenFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipality/contractor-invoices': {
      id: '/municipality/contractor-invoices'
      path: '/municipality/contractor-invoices'
      fullPath: '/municipality/contractor-invoices'
      preLoaderRoute: typeof MunicipalityContractorInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipality/sla-breach': {
      id: '/municipality/sla-breach'
      path: '/municipality/sla-breach'
      fullPath: '/municipality/sla-breach'
      preLoaderRoute: typeof MunicipalitySlaBreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/areas/': {
      id: '/_auth/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthAreasIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/civic-issues/': {
      id: '/_auth/civic-issues/'
      path: '/civic-issues'
      fullPath: '/civic-issues/'
      preLoaderRoute: typeof AuthCivicIssuesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/civic-issues/$id': {
      id: '/_auth/civic-issues/$id'
      path: '/civic-issues/$id'
      fullPath: '/civic-issues/$id'
      preLoaderRoute: typeof AuthCivicIssuesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/complaints/': {
      id: '/_auth/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthComplaintsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/complaints/$id': {
      id: '/_auth/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthComplaintsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/departments/': {
      id: '/_auth/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AuthDepartmentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/departments/$id': {
      id: '/_auth/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof AuthDepartmentsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/issues/': {
      id: '/_auth/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthIssuesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/issues/$id': {
      id: '/_auth/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthIssuesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenders/': {
      id: '/_auth/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof AuthTendersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenders/$id': {
      id: '/_auth/tenders/$id'
      path: '/tenders/$id'
      fullPath: '/tenders/$id'
      preLoaderRoute: typeof AuthTendersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenders/new': {
      id: '/_auth/tenders/new'
      path: '/tenders/new'
      fullPath: '/tenders/new'
      preLoaderRoute: typeof AuthTendersNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-orders/': {
      id: '/_auth/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AuthWorkOrdersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-orders/$id': {
      id: '/_auth/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof AuthWorkOrdersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAdministrationRoute: typeof AuthAdministrationRoute
  AuthAiTriageRoute: typeof AuthAiTriageRoute
  AuthAlertsRoute: typeof AuthAlertsRoute
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMapRoute: typeof AuthMapRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWorkPackagesRoute: typeof AuthWorkPackagesRoute
  AuthCivicIssuesIdRoute: typeof AuthCivicIssuesIdRoute
  AuthComplaintsIdRoute: typeof AuthComplaintsIdRoute
  AuthDepartmentsIdRoute: typeof AuthDepartmentsIdRoute
  AuthIssuesIdRoute: typeof AuthIssuesIdRoute
  AuthTendersIdRoute: typeof AuthTendersIdRoute
  AuthTendersNewRoute: typeof AuthTendersNewRoute
  AuthWorkOrdersIdRoute: typeof AuthWorkOrdersIdRoute
  AuthAreasIndexRoute: typeof AuthAreasIndexRoute
  AuthCivicIssuesIndexRoute: typeof AuthCivicIssuesIndexRoute
  AuthComplaintsIndexRoute: typeof AuthComplaintsIndexRoute
  AuthDepartmentsIndexRoute: typeof AuthDepartmentsIndexRoute
  AuthIssuesIndexRoute: typeof AuthIssuesIndexRoute
  AuthTendersIndexRoute: typeof AuthTendersIndexRoute
  AuthWorkOrdersIndexRoute: typeof AuthWorkOrdersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdministrationRoute: AuthAdministrationRoute,
  AuthAiTriageRoute: AuthAiTriageRoute,
  AuthAlertsRoute: AuthAlertsRoute,
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMapRoute: AuthMapRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWorkPackagesRoute: AuthWorkPackagesRoute,
  AuthCivicIssuesIdRoute: AuthCivicIssuesIdRoute,
  AuthComplaintsIdRoute: AuthComplaintsIdRoute,
  AuthDepartmentsIdRoute: AuthDepartmentsIdRoute,
  AuthIssuesIdRoute: AuthIssuesIdRoute,
  AuthTendersIdRoute: AuthTendersIdRoute,
  AuthTendersNewRoute: AuthTendersNewRoute,
  AuthWorkOrdersIdRoute: AuthWorkOrdersIdRoute,
  AuthAreasIndexRoute: AuthAreasIndexRoute,
  AuthCivicIssuesIndexRoute: AuthCivicIssuesIndexRoute,
  AuthComplaintsIndexRoute: AuthComplaintsIndexRoute,
  AuthDepartmentsIndexRoute: AuthDepartmentsIndexRoute,
  AuthIssuesIndexRoute: AuthIssuesIndexRoute,
  AuthTendersIndexRoute: AuthTendersIndexRoute,
  AuthWorkOrdersIndexRoute: AuthWorkOrdersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MunicipalityAnalyticsRoute: MunicipalityAnalyticsRoute,
  MunicipalityCitizenFeedbackRoute: MunicipalityCitizenFeedbackRoute,
  MunicipalityContractorInvoicesRoute: MunicipalityContractorInvoicesRoute,
  MunicipalitySlaBreachRoute: MunicipalitySlaBreachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
