/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthAiTriageRouteImport } from './routes/_auth/ai-triage'
import { Route as AuthAlertsRouteImport } from './routes/_auth/alerts'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthAreasIndexRouteImport } from './routes/_auth/areas/index'
import { Route as AuthCivicIssuesIndexRouteImport } from './routes/_auth/civic-issues/index'
import { Route as AuthCivicIssuesIdRouteImport } from './routes/_auth/civic-issues/$id'
import { Route as AuthComplaintsIndexRouteImport } from './routes/_auth/complaints/index'
import { Route as AuthComplaintsIdRouteImport } from './routes/_auth/complaints/$id'
import { Route as AuthDepartmentsIndexRouteImport } from './routes/_auth/departments/index'
import { Route as AuthDepartmentsIdRouteImport } from './routes/_auth/departments/$id'
import { Route as AuthIssuesIndexRouteImport } from './routes/_auth/issues/index'
import { Route as AuthIssuesIdRouteImport } from './routes/_auth/issues/$id'
import { Route as AuthWorkOrdersIndexRouteImport } from './routes/_auth/work-orders/index'
import { Route as AuthWorkOrdersIdRouteImport } from './routes/_auth/work-orders/$id'
import { Route as AuthWorkPackagesIndexRouteImport } from './routes/_auth/work-packages/index'
import { Route as AuthWorkPackagesIdRouteImport } from './routes/_auth/work-packages/$id'
import { Route as AuthWorkPackagesNewRouteImport } from './routes/_auth/work-packages/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAiTriageRoute = AuthAiTriageRouteImport.update({
  id: '/ai-triage',
  path: '/ai-triage',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlertsRoute = AuthAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAreasIndexRoute = AuthAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCivicIssuesIndexRoute = AuthCivicIssuesIndexRouteImport.update({
  id: '/civic-issues/',
  path: '/civic-issues/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCivicIssuesIdRoute = AuthCivicIssuesIdRouteImport.update({
  id: '/civic-issues/$id',
  path: '/civic-issues/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthComplaintsIndexRoute = AuthComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthComplaintsIdRoute = AuthComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDepartmentsIndexRoute = AuthDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDepartmentsIdRoute = AuthDepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIssuesIndexRoute = AuthIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIssuesIdRoute = AuthIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkOrdersIndexRoute = AuthWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkOrdersIdRoute = AuthWorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkPackagesIndexRoute = AuthWorkPackagesIndexRouteImport.update({
  id: '/work-packages/',
  path: '/work-packages/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkPackagesIdRoute = AuthWorkPackagesIdRouteImport.update({
  id: '/work-packages/$id',
  path: '/work-packages/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkPackagesNewRoute = AuthWorkPackagesNewRouteImport.update({
  id: '/work-packages/new',
  path: '/work-packages/new',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-triage': typeof AuthAiTriageRoute
  '/alerts': typeof AuthAlertsRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/map': typeof AuthMapRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/complaints/$id': typeof AuthComplaintsIdRoute
  '/departments/$id': typeof AuthDepartmentsIdRoute
  '/issues/$id': typeof AuthIssuesIdRoute
  '/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/work-packages/$id': typeof AuthWorkPackagesIdRoute
  '/work-packages/new': typeof AuthWorkPackagesNewRoute
  '/areas/': typeof AuthAreasIndexRoute
  '/civic-issues/': typeof AuthCivicIssuesIndexRoute
  '/complaints/': typeof AuthComplaintsIndexRoute
  '/departments/': typeof AuthDepartmentsIndexRoute
  '/issues/': typeof AuthIssuesIndexRoute
  '/work-orders/': typeof AuthWorkOrdersIndexRoute
  '/work-packages/': typeof AuthWorkPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-triage': typeof AuthAiTriageRoute
  '/alerts': typeof AuthAlertsRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/map': typeof AuthMapRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/complaints/$id': typeof AuthComplaintsIdRoute
  '/departments/$id': typeof AuthDepartmentsIdRoute
  '/issues/$id': typeof AuthIssuesIdRoute
  '/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/work-packages/$id': typeof AuthWorkPackagesIdRoute
  '/work-packages/new': typeof AuthWorkPackagesNewRoute
  '/areas': typeof AuthAreasIndexRoute
  '/civic-issues': typeof AuthCivicIssuesIndexRoute
  '/complaints': typeof AuthComplaintsIndexRoute
  '/departments': typeof AuthDepartmentsIndexRoute
  '/issues': typeof AuthIssuesIndexRoute
  '/work-orders': typeof AuthWorkOrdersIndexRoute
  '/work-packages': typeof AuthWorkPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/ai-triage': typeof AuthAiTriageRoute
  '/_auth/alerts': typeof AuthAlertsRoute
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/civic-issues/$id': typeof AuthCivicIssuesIdRoute
  '/_auth/complaints/$id': typeof AuthComplaintsIdRoute
  '/_auth/departments/$id': typeof AuthDepartmentsIdRoute
  '/_auth/issues/$id': typeof AuthIssuesIdRoute
  '/_auth/work-orders/$id': typeof AuthWorkOrdersIdRoute
  '/_auth/work-packages/$id': typeof AuthWorkPackagesIdRoute
  '/_auth/work-packages/new': typeof AuthWorkPackagesNewRoute
  '/_auth/areas/': typeof AuthAreasIndexRoute
  '/_auth/civic-issues/': typeof AuthCivicIssuesIndexRoute
  '/_auth/complaints/': typeof AuthComplaintsIndexRoute
  '/_auth/departments/': typeof AuthDepartmentsIndexRoute
  '/_auth/issues/': typeof AuthIssuesIndexRoute
  '/_auth/work-orders/': typeof AuthWorkOrdersIndexRoute
  '/_auth/work-packages/': typeof AuthWorkPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-triage'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/settings'
    | '/civic-issues/$id'
    | '/complaints/$id'
    | '/departments/$id'
    | '/issues/$id'
    | '/work-orders/$id'
    | '/work-packages/$id'
    | '/work-packages/new'
    | '/areas/'
    | '/civic-issues/'
    | '/complaints/'
    | '/departments/'
    | '/issues/'
    | '/work-orders/'
    | '/work-packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-triage'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/settings'
    | '/civic-issues/$id'
    | '/complaints/$id'
    | '/departments/$id'
    | '/issues/$id'
    | '/work-orders/$id'
    | '/work-packages/$id'
    | '/work-packages/new'
    | '/areas'
    | '/civic-issues'
    | '/complaints'
    | '/departments'
    | '/issues'
    | '/work-orders'
    | '/work-packages'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/ai-triage'
    | '/_auth/alerts'
    | '/_auth/analytics'
    | '/_auth/dashboard'
    | '/_auth/map'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/civic-issues/$id'
    | '/_auth/complaints/$id'
    | '/_auth/departments/$id'
    | '/_auth/issues/$id'
    | '/_auth/work-orders/$id'
    | '/_auth/work-packages/$id'
    | '/_auth/work-packages/new'
    | '/_auth/areas/'
    | '/_auth/civic-issues/'
    | '/_auth/complaints/'
    | '/_auth/departments/'
    | '/_auth/issues/'
    | '/_auth/work-orders/'
    | '/_auth/work-packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/ai-triage': {
      id: '/_auth/ai-triage'
      path: '/ai-triage'
      fullPath: '/ai-triage'
      preLoaderRoute: typeof AuthAiTriageRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/alerts': {
      id: '/_auth/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthAlertsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/areas/': {
      id: '/_auth/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthAreasIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/civic-issues/': {
      id: '/_auth/civic-issues/'
      path: '/civic-issues'
      fullPath: '/civic-issues/'
      preLoaderRoute: typeof AuthCivicIssuesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/civic-issues/$id': {
      id: '/_auth/civic-issues/$id'
      path: '/civic-issues/$id'
      fullPath: '/civic-issues/$id'
      preLoaderRoute: typeof AuthCivicIssuesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/complaints/': {
      id: '/_auth/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthComplaintsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/complaints/$id': {
      id: '/_auth/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthComplaintsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/departments/': {
      id: '/_auth/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AuthDepartmentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/departments/$id': {
      id: '/_auth/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof AuthDepartmentsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/issues/': {
      id: '/_auth/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthIssuesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/issues/$id': {
      id: '/_auth/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthIssuesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-orders/': {
      id: '/_auth/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AuthWorkOrdersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-orders/$id': {
      id: '/_auth/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof AuthWorkOrdersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-packages/': {
      id: '/_auth/work-packages/'
      path: '/work-packages'
      fullPath: '/work-packages/'
      preLoaderRoute: typeof AuthWorkPackagesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-packages/$id': {
      id: '/_auth/work-packages/$id'
      path: '/work-packages/$id'
      fullPath: '/work-packages/$id'
      preLoaderRoute: typeof AuthWorkPackagesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/work-packages/new': {
      id: '/_auth/work-packages/new'
      path: '/work-packages/new'
      fullPath: '/work-packages/new'
      preLoaderRoute: typeof AuthWorkPackagesNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAiTriageRoute: typeof AuthAiTriageRoute
  AuthAlertsRoute: typeof AuthAlertsRoute
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMapRoute: typeof AuthMapRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthCivicIssuesIdRoute: typeof AuthCivicIssuesIdRoute
  AuthComplaintsIdRoute: typeof AuthComplaintsIdRoute
  AuthDepartmentsIdRoute: typeof AuthDepartmentsIdRoute
  AuthIssuesIdRoute: typeof AuthIssuesIdRoute
  AuthWorkOrdersIdRoute: typeof AuthWorkOrdersIdRoute
  AuthWorkPackagesIdRoute: typeof AuthWorkPackagesIdRoute
  AuthWorkPackagesNewRoute: typeof AuthWorkPackagesNewRoute
  AuthAreasIndexRoute: typeof AuthAreasIndexRoute
  AuthCivicIssuesIndexRoute: typeof AuthCivicIssuesIndexRoute
  AuthComplaintsIndexRoute: typeof AuthComplaintsIndexRoute
  AuthDepartmentsIndexRoute: typeof AuthDepartmentsIndexRoute
  AuthIssuesIndexRoute: typeof AuthIssuesIndexRoute
  AuthWorkOrdersIndexRoute: typeof AuthWorkOrdersIndexRoute
  AuthWorkPackagesIndexRoute: typeof AuthWorkPackagesIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAiTriageRoute: AuthAiTriageRoute,
  AuthAlertsRoute: AuthAlertsRoute,
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMapRoute: AuthMapRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthCivicIssuesIdRoute: AuthCivicIssuesIdRoute,
  AuthComplaintsIdRoute: AuthComplaintsIdRoute,
  AuthDepartmentsIdRoute: AuthDepartmentsIdRoute,
  AuthIssuesIdRoute: AuthIssuesIdRoute,
  AuthWorkOrdersIdRoute: AuthWorkOrdersIdRoute,
  AuthWorkPackagesIdRoute: AuthWorkPackagesIdRoute,
  AuthWorkPackagesNewRoute: AuthWorkPackagesNewRoute,
  AuthAreasIndexRoute: AuthAreasIndexRoute,
  AuthCivicIssuesIndexRoute: AuthCivicIssuesIndexRoute,
  AuthComplaintsIndexRoute: AuthComplaintsIndexRoute,
  AuthDepartmentsIndexRoute: AuthDepartmentsIndexRoute,
  AuthIssuesIndexRoute: AuthIssuesIndexRoute,
  AuthWorkOrdersIndexRoute: AuthWorkOrdersIndexRoute,
  AuthWorkPackagesIndexRoute: AuthWorkPackagesIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
