/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractorRouteRouteImport } from './routes/contractor/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContractorDashboardRouteImport } from './routes/contractor/dashboard'
import { Route as ContractorPerformanceRouteImport } from './routes/contractor/performance'
import { Route as ContractorProfileRouteImport } from './routes/contractor/profile'
import { Route as ContractorTendersIndexRouteImport } from './routes/contractor/tenders/index'
import { Route as ContractorTendersIdRouteImport } from './routes/contractor/tenders/$id'
import { Route as ContractorWorkOrdersIndexRouteImport } from './routes/contractor/work-orders/index'
import { Route as ContractorWorkOrdersIdRouteImport } from './routes/contractor/work-orders/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRouteRoute = ContractorRouteRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorDashboardRoute = ContractorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorPerformanceRoute = ContractorPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorTendersIndexRoute = ContractorTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorTendersIdRoute = ContractorTendersIdRouteImport.update({
  id: '/tenders/$id',
  path: '/tenders/$id',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorWorkOrdersIndexRoute =
  ContractorWorkOrdersIndexRouteImport.update({
    id: '/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => ContractorRouteRoute,
  } as any)
const ContractorWorkOrdersIdRoute = ContractorWorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => ContractorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/performance': typeof ContractorPerformanceRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/tenders/$id': typeof ContractorTendersIdRoute
  '/contractor/work-orders/$id': typeof ContractorWorkOrdersIdRoute
  '/contractor/tenders/': typeof ContractorTendersIndexRoute
  '/contractor/work-orders/': typeof ContractorWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/performance': typeof ContractorPerformanceRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/tenders/$id': typeof ContractorTendersIdRoute
  '/contractor/work-orders/$id': typeof ContractorWorkOrdersIdRoute
  '/contractor/tenders': typeof ContractorTendersIndexRoute
  '/contractor/work-orders': typeof ContractorWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/performance': typeof ContractorPerformanceRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/tenders/$id': typeof ContractorTendersIdRoute
  '/contractor/work-orders/$id': typeof ContractorWorkOrdersIdRoute
  '/contractor/tenders/': typeof ContractorTendersIndexRoute
  '/contractor/work-orders/': typeof ContractorWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contractor'
    | '/forgot-password'
    | '/login'
    | '/contractor/dashboard'
    | '/contractor/performance'
    | '/contractor/profile'
    | '/contractor/tenders/$id'
    | '/contractor/work-orders/$id'
    | '/contractor/tenders/'
    | '/contractor/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contractor'
    | '/forgot-password'
    | '/login'
    | '/contractor/dashboard'
    | '/contractor/performance'
    | '/contractor/profile'
    | '/contractor/tenders/$id'
    | '/contractor/work-orders/$id'
    | '/contractor/tenders'
    | '/contractor/work-orders'
  id:
    | '__root__'
    | '/'
    | '/contractor'
    | '/forgot-password'
    | '/login'
    | '/contractor/dashboard'
    | '/contractor/performance'
    | '/contractor/profile'
    | '/contractor/tenders/$id'
    | '/contractor/work-orders/$id'
    | '/contractor/tenders/'
    | '/contractor/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractorRouteRoute: typeof ContractorRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/dashboard': {
      id: '/contractor/dashboard'
      path: '/dashboard'
      fullPath: '/contractor/dashboard'
      preLoaderRoute: typeof ContractorDashboardRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/performance': {
      id: '/contractor/performance'
      path: '/performance'
      fullPath: '/contractor/performance'
      preLoaderRoute: typeof ContractorPerformanceRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/profile': {
      id: '/contractor/profile'
      path: '/profile'
      fullPath: '/contractor/profile'
      preLoaderRoute: typeof ContractorProfileRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/tenders/': {
      id: '/contractor/tenders/'
      path: '/tenders'
      fullPath: '/contractor/tenders/'
      preLoaderRoute: typeof ContractorTendersIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/tenders/$id': {
      id: '/contractor/tenders/$id'
      path: '/tenders/$id'
      fullPath: '/contractor/tenders/$id'
      preLoaderRoute: typeof ContractorTendersIdRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/work-orders/': {
      id: '/contractor/work-orders/'
      path: '/work-orders'
      fullPath: '/contractor/work-orders/'
      preLoaderRoute: typeof ContractorWorkOrdersIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/work-orders/$id': {
      id: '/contractor/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/contractor/work-orders/$id'
      preLoaderRoute: typeof ContractorWorkOrdersIdRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
  }
}

interface ContractorRouteRouteChildren {
  ContractorDashboardRoute: typeof ContractorDashboardRoute
  ContractorPerformanceRoute: typeof ContractorPerformanceRoute
  ContractorProfileRoute: typeof ContractorProfileRoute
  ContractorTendersIdRoute: typeof ContractorTendersIdRoute
  ContractorWorkOrdersIdRoute: typeof ContractorWorkOrdersIdRoute
  ContractorTendersIndexRoute: typeof ContractorTendersIndexRoute
  ContractorWorkOrdersIndexRoute: typeof ContractorWorkOrdersIndexRoute
}

const ContractorRouteRouteChildren: ContractorRouteRouteChildren = {
  ContractorDashboardRoute: ContractorDashboardRoute,
  ContractorPerformanceRoute: ContractorPerformanceRoute,
  ContractorProfileRoute: ContractorProfileRoute,
  ContractorTendersIdRoute: ContractorTendersIdRoute,
  ContractorWorkOrdersIdRoute: ContractorWorkOrdersIdRoute,
  ContractorTendersIndexRoute: ContractorTendersIndexRoute,
  ContractorWorkOrdersIndexRoute: ContractorWorkOrdersIndexRoute,
}

const ContractorRouteRouteWithChildren = ContractorRouteRoute._addFileChildren(
  ContractorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractorRouteRoute: ContractorRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
