"""State Command Center Service — Govt. of Maharashtra (SIH26129).

Aggregates state-wide telemetry across 27 Municipal Corporations, 143 Sovereign Departments,
and Sathi Setu Interoperability Brokers.
"""

from typing import Any, Dict, List
from datetime import datetime, timezone


MAHARASHTRA_CORPORATIONS = [
    {
        "id": "mcgm",
        "name": "Brihanmumbai Municipal Corporation (MCGM)",
        "city": "Mumbai",
        "division": "Konkan",
        "lat": 18.9402,
        "lng": 72.8347,
        "active_cases": 4210,
        "resolved_rate": 93.8,
        "connected_depts": 8,
        "critical_cascades": 28,
        "taxpayer_savings_cr": 1.45,
        "status": "HEALTHY",
    },
    {
        "id": "pmc",
        "name": "Pune Municipal Corporation (PMC)",
        "city": "Pune",
        "division": "Pune",
        "lat": 18.5204,
        "lng": 73.8567,
        "active_cases": 2890,
        "resolved_rate": 95.1,
        "connected_depts": 7,
        "critical_cascades": 16,
        "taxpayer_savings_cr": 0.98,
        "status": "HEALTHY",
    },
    {
        "id": "nmc_nagpur",
        "name": "Nagpur Municipal Corporation (NMC)",
        "city": "Nagpur",
        "division": "Nagpur",
        "lat": 21.1458,
        "lng": 79.0882,
        "active_cases": 1720,
        "resolved_rate": 92.4,
        "connected_depts": 6,
        "critical_cascades": 14,
        "taxpayer_savings_cr": 0.62,
        "status": "HEALTHY",
    },
    {
        "id": "tmc",
        "name": "Thane Municipal Corporation (TMC)",
        "city": "Thane",
        "division": "Konkan",
        "lat": 19.2183,
        "lng": 72.9781,
        "active_cases": 1540,
        "resolved_rate": 94.0,
        "connected_depts": 6,
        "critical_cascades": 11,
        "taxpayer_savings_cr": 0.44,
        "status": "HEALTHY",
    },
    {
        "id": "pcmc",
        "name": "Pimpri-Chinchwad Municipal Corporation (PCMC)",
        "city": "Pimpri-Chinchwad",
        "division": "Pune",
        "lat": 18.6298,
        "lng": 73.7997,
        "active_cases": 1380,
        "resolved_rate": 96.2,
        "connected_depts": 6,
        "critical_cascades": 8,
        "taxpayer_savings_cr": 0.41,
        "status": "HEALTHY",
    },
    {
        "id": "nmc_nashik",
        "name": "Nashik Municipal Corporation",
        "city": "Nashik",
        "division": "Nashik",
        "lat": 19.9975,
        "lng": 73.7898,
        "active_cases": 1120,
        "resolved_rate": 91.8,
        "connected_depts": 5,
        "critical_cascades": 12,
        "taxpayer_savings_cr": 0.31,
        "status": "ATTENTION_REQUIRED",
    },
    {
        "id": "vvcmc",
        "name": "Vasai-Virar City Municipal Corporation (VVCMC)",
        "city": "Vasai-Virar",
        "division": "Konkan",
        "lat": 19.3919,
        "lng": 72.8397,
        "active_cases": 980,
        "resolved_rate": 90.5,
        "connected_depts": 5,
        "critical_cascades": 9,
        "taxpayer_savings_cr": 0.28,
        "status": "HEALTHY",
    },
    {
        "id": "amc",
        "name": "Chhatrapati Sambhajinagar Municipal Corporation",
        "city": "Chhatrapati Sambhajinagar",
        "division": "Marathwada",
        "lat": 19.8762,
        "lng": 75.3433,
        "active_cases": 860,
        "resolved_rate": 93.1,
        "connected_depts": 5,
        "critical_cascades": 7,
        "taxpayer_savings_cr": 0.21,
        "status": "HEALTHY",
    },
    {
        "id": "nmmc",
        "name": "Navi Mumbai Municipal Corporation (NMMC)",
        "city": "Navi Mumbai",
        "division": "Konkan",
        "lat": 19.0330,
        "lng": 73.0297,
        "active_cases": 1150,
        "resolved_rate": 97.4,
        "connected_depts": 7,
        "critical_cascades": 5,
        "taxpayer_savings_cr": 0.34,
        "status": "HEALTHY",
    },
    {
        "id": "kdmc",
        "name": "Kalyan-Dombivli Municipal Corporation (KDMC)",
        "city": "Kalyan",
        "division": "Konkan",
        "lat": 19.2403,
        "lng": 73.1305,
        "active_cases": 1240,
        "resolved_rate": 89.2,
        "connected_depts": 5,
        "critical_cascades": 17,
        "taxpayer_savings_cr": 0.28,
        "status": "ATTENTION_REQUIRED",
    },
]

DIGITAL_TWIN_CRITICAL_INCIDENTS = [
    {
        "id": "MH-MCGM-2026-080596",
        "city": "Mumbai",
        "ward": "Ward H-West (Bandra West)",
        "title": "High-Pressure Water Conduit Rupture & Road Subsidence",
        "location": "SV Road, Near Bandra Station West",
        "lat": 19.0596,
        "lng": 72.8295,
        "severity": "CRITICAL",
        "priority": "P1",
        "status": "SEQUENCED_ORCHESTRATION",
        "departments": ["Water Supply Board", "PWD Roads Division"],
        "cost_multiplier": 12.3,
        "affected_citizens": 42500,
        "impact_radius_km": 1.85,
    },
    {
        "id": "MH-PMC-2026-114920",
        "city": "Pune",
        "ward": "Kothrud Ward 12",
        "title": "Stormwater Culvert Collapse Threatening Power Substation",
        "location": "Paud Road, Kothrud",
        "lat": 18.5074,
        "lng": 73.8077,
        "severity": "HIGH",
        "priority": "P1",
        "status": "AWAITING_DRAINAGE_DESILT",
        "departments": ["Stormwater Drainage", "MSEDCL Power Distribution", "PMC Roads"],
        "cost_multiplier": 8.5,
        "affected_citizens": 28000,
        "impact_radius_km": 1.4,
    },
    {
        "id": "MH-NMC-2026-092184",
        "city": "Nagpur",
        "ward": "Dharampeth Zone",
        "title": "Main Feeder Pipeline Burst Beneath Arterial Junction",
        "location": "Amravati Road Junction",
        "lat": 21.1524,
        "lng": 79.0558,
        "severity": "HIGH",
        "priority": "P2",
        "status": "WATER_CREW_DEPLOYED",
        "departments": ["Water Board", "NMC PWD"],
        "cost_multiplier": 6.2,
        "affected_citizens": 19200,
        "impact_radius_km": 0.95,
    },
    {
        "id": "MH-TMC-2026-041928",
        "city": "Thane",
        "ward": "Naupada-Kopri Ward",
        "title": "Subgrade Soil Erosion Under Flyover Pier",
        "location": "Gokhale Road, Thane West",
        "lat": 19.1902,
        "lng": 72.9734,
        "severity": "CRITICAL",
        "priority": "P1",
        "status": "EMERGENCY_SHORING",
        "departments": ["MMRDA Infrastructure", "PWD Bridges", "Thane Water"],
        "cost_multiplier": 14.1,
        "affected_citizens": 65000,
        "impact_radius_km": 2.2,
    },
]


def get_state_command_center_telemetry() -> Dict[str, Any]:
    """
    Returns state-wide aggregated command center intelligence for the Government of Maharashtra.
    """
    total_active = sum(c["active_cases"] for c in MAHARASHTRA_CORPORATIONS)
    avg_resolution = round(
        sum(c["resolved_rate"] for c in MAHARASHTRA_CORPORATIONS) / len(MAHARASHTRA_CORPORATIONS), 1
    )
    total_savings_cr = round(sum(c["taxpayer_savings_cr"] for c in MAHARASHTRA_CORPORATIONS), 2)
    total_critical = sum(c["critical_cascades"] for c in MAHARASHTRA_CORPORATIONS)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "state_name": "Maharashtra",
        "protocol": "SIH26129 Macro Interoperability Standard",
        "architecture": "MeitY API Setu / Estonia X-Road Sovereign Gateway",
        "summary": {
            "total_municipal_corporations": 27,
            "monitored_municipalities": len(MAHARASHTRA_CORPORATIONS),
            "total_sovereign_departments": 143,
            "total_active_cases": total_active,
            "average_resolution_rate": avg_resolution,
            "critical_systemic_cascades": total_critical,
            "average_inter_agency_latency_ms": 34.2,
            "estimated_taxpayer_savings_cr": total_savings_cr,
            "sla_compliance_rate": 92.6,
        },
        "corporations": MAHARASHTRA_CORPORATIONS,
        "critical_incidents": DIGITAL_TWIN_CRITICAL_INCIDENTS,
        "digital_twin_layers": [
            {
                "id": "critical_cascades",
                "name": "Critical Inter-Agency Cascades",
                "count": total_critical,
                "color": "#F43F5E",
            },
            {
                "id": "active_work_orders",
                "name": "Sovereign Work Orders in Transit",
                "count": total_active,
                "color": "#0A369D",
            },
            {
                "id": "risk_perimeters",
                "name": "Predicted Collapse Risk Perimeters",
                "count": len(DIGITAL_TWIN_CRITICAL_INCIDENTS),
                "color": "#FF6F00",
            },
        ],
    }
