"""contractor_governance

Revision ID: 0adc54e0e7ad
Revises: 326bdd8f9ffc
Create Date: 2026-08-16 16:29:18.354364

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0adc54e0e7ad'
down_revision: Union[str, None] = '326bdd8f9ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_city_registrations', sa.Column('current_risk_level', sa.String(length=20), nullable=False))
    op.add_column('work_orders', sa.Column('planned_progress_pct', sa.Float(), nullable=False))
    op.add_column('work_orders', sa.Column('reported_progress_pct', sa.Float(), nullable=False))
    op.add_column('work_orders', sa.Column('verified_progress_pct', sa.Float(), nullable=False))
    op.add_column('work_orders', sa.Column('risk_level', sa.String(length=20), nullable=False))
    op.add_column('work_orders', sa.Column('risk_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('work_orders', sa.Column('defect_liability_period_days', sa.Integer(), nullable=False))
    op.add_column('work_orders', sa.Column('liquidated_damages_pct_per_day', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'liquidated_damages_pct_per_day')
    op.drop_column('work_orders', 'defect_liability_period_days')
    op.drop_column('work_orders', 'risk_reasons')
    op.drop_column('work_orders', 'risk_level')
    op.drop_column('work_orders', 'verified_progress_pct')
    op.drop_column('work_orders', 'reported_progress_pct')
    op.drop_column('work_orders', 'planned_progress_pct')
    op.drop_column('contractor_city_registrations', 'current_risk_level')
    # ### end Alembic commands ###
