"""Add GPS Evidence, Bills, Bid Documents

Revision ID: 2061ce6b855e
Revises: 20260822_master_case_routing
Create Date: 2026-09-14 13:42:57.882436

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2061ce6b855e'
down_revision: Union[str, None] = '20260822_master_case_routing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_city_id'), 'zones', ['city_id'], unique=False)
    op.create_table('bills',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VERIFIED', 'APPROVED', 'PAID', 'REJECTED', name='billstatus'), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('payment_utr', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_contractor_id'), 'bills', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_bills_status'), 'bills', ['status'], unique=False)
    op.create_index(op.f('ix_bills_work_order_id'), 'bills', ['work_order_id'], unique=False)
    op.add_column('bids', sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_case_departments_dependency_id'), table_name='case_departments')
    op.create_index(op.f('ix_case_departments_dependency_case_dept_id'), 'case_departments', ['dependency_case_dept_id'], unique=False)
    op.drop_constraint(op.f('civic_cases_case_number_key'), 'civic_cases', type_='unique')
    op.create_index(op.f('ix_civic_cases_priority'), 'civic_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_civic_cases_severity'), 'civic_cases', ['severity'], unique=False)
    op.create_index(op.f('ix_civic_cases_status'), 'civic_cases', ['status'], unique=False)
    op.alter_column('contractors', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('contractors', 'public_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.5'))
    op.alter_column('contractors', 'ai_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.8'))
    op.alter_column('contractors', 'officer_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.6'))
    op.add_column('field_evidence', sa.Column('milestone_name', sa.String(length=255), nullable=True))
    op.add_column('field_evidence', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('field_evidence', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('field_evidence', sa.Column('gps_lng', sa.Float(), nullable=True))
    op.add_column('field_evidence', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('wards', 'city_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_wards_city_id'), 'wards', ['city_id'], unique=False)
    op.create_index(op.f('ix_wards_zone_id'), 'wards', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'wards', 'zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wards', type_='foreignkey')
    op.drop_index(op.f('ix_wards_zone_id'), table_name='wards')
    op.drop_index(op.f('ix_wards_city_id'), table_name='wards')
    op.alter_column('wards', 'city_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('field_evidence', 'captured_at')
    op.drop_column('field_evidence', 'gps_lng')
    op.drop_column('field_evidence', 'gps_lat')
    op.drop_column('field_evidence', 'stage')
    op.drop_column('field_evidence', 'milestone_name')
    op.alter_column('contractors', 'officer_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.6'))
    op.alter_column('contractors', 'ai_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.8'))
    op.alter_column('contractors', 'public_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.5'))
    op.alter_column('contractors', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_civic_cases_status'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_severity'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_priority'), table_name='civic_cases')
    op.create_unique_constraint(op.f('civic_cases_case_number_key'), 'civic_cases', ['case_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_case_departments_dependency_case_dept_id'), table_name='case_departments')
    op.create_index(op.f('ix_case_departments_dependency_id'), 'case_departments', ['dependency_case_dept_id'], unique=False)
    op.drop_column('bids', 'documents')
    op.drop_index(op.f('ix_bills_work_order_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_contractor_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_zones_city_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
