"""Add procurement models

Revision ID: 240c255c0a26
Revises: 4f3e5295f6d8
Create Date: 2026-08-16 15:18:09.007333

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240c255c0a26'
down_revision: Union[str, None] = '4f3e5295f6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractors',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('auth_user_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_auth_user_id'), 'contractors', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_contractors_email'), 'contractors', ['email'], unique=True)
    op.create_index(op.f('ix_contractors_phone'), 'contractors', ['phone'], unique=False)
    op.create_table('contractor_city_registrations',
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('registration_class', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REVOKED', name='registrationstatus'), nullable=False),
    sa.Column('approved_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_city_registrations_city_id'), 'contractor_city_registrations', ['city_id'], unique=False)
    op.create_index(op.f('ix_contractor_city_registrations_contractor_id'), 'contractor_city_registrations', ['contractor_id'], unique=False)
    op.create_table('tenders',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('civic_issue_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('estimated_budget', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'EVALUATING', 'AWARDED', 'CANCELLED', name='tenderstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['civic_issue_id'], ['issue_clusters.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_city_id'), 'tenders', ['city_id'], unique=False)
    op.create_index(op.f('ix_tenders_department_id'), 'tenders', ['department_id'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_table('bids',
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('quoted_amount', sa.Float(), nullable=False),
    sa.Column('technical_proposal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'QUALIFIED', 'REJECTED', 'WON', name='bidstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_contractor_id'), 'bids', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_index(op.f('ix_bids_tender_id'), 'bids', ['tender_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('bid_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('award_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'ACCEPTED', 'IN_PROGRESS', 'INSPECTION_PENDING', 'COMPLETED', 'CLOSED', name='workorderstatus'), nullable=False),
    sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_contractor_id'), 'work_orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_tender_id'), 'work_orders', ['tender_id'], unique=False)
    op.create_table('field_evidence',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_evidence_work_order_id'), 'field_evidence', ['work_order_id'], unique=False)
    op.create_table('inspections',
    sa.Column('field_evidence_id', sa.UUID(), nullable=False),
    sa.Column('inspector_user_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'REWORK', 'FAIL', name='inspectionresult'), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_evidence_id'], ['field_evidence.id'], ),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_field_evidence_id'), 'inspections', ['field_evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_field_evidence_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_field_evidence_work_order_id'), table_name='field_evidence')
    op.drop_table('field_evidence')
    op.drop_index(op.f('ix_work_orders_tender_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_contractor_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_bids_tender_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index(op.f('ix_bids_contractor_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_department_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_city_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_contractor_city_registrations_contractor_id'), table_name='contractor_city_registrations')
    op.drop_index(op.f('ix_contractor_city_registrations_city_id'), table_name='contractor_city_registrations')
    op.drop_table('contractor_city_registrations')
    op.drop_index(op.f('ix_contractors_phone'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_email'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_auth_user_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_table('cities')
    # ### end Alembic commands ###
