"""city_not_null

Revision ID: 326bdd8f9ffc
Revises: 73746b6761b7
Create Date: 2026-08-16 16:13:34.737707

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326bdd8f9ffc'
down_revision: Union[str, None] = '73746b6761b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'city_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('issue_clusters', 'city_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue_clusters', 'city_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('complaints', 'city_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
