"""add complaint public id sequence

Revision ID: 4f3e5295f6d8
Revises: 754d4a098e0d
Create Date: 2026-08-13 20:17:16.629977

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3e5295f6d8'
down_revision: Union[str, None] = '754d4a098e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the sequence first
    op.execute("CREATE SEQUENCE IF NOT EXISTS complaint_public_seq START WITH 1")
    
    # Add column as nullable first (without server default to avoid auto-assignment)
    op.add_column('complaints', sa.Column('public_id_seq', sa.Integer(), nullable=True))
    
    # Backfill existing complaints with sequential numbers based on creation order
    op.execute("""
        WITH ranked_complaints AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) as rn
            FROM complaints
        )
        UPDATE complaints c
        SET public_id_seq = rc.rn
        FROM ranked_complaints rc
        WHERE c.id = rc.id
    """)
    
    # Update the sequence to continue from the max value
    op.execute("""
        SELECT setval('complaint_public_seq', COALESCE((SELECT MAX(public_id_seq) FROM complaints), 0) + 1, false)
    """)
    
    # Update public_id to match the new format (JN-YYYY-NNNNN)
    op.execute("""
        UPDATE complaints
        SET public_id = 'JN-' || EXTRACT(YEAR FROM created_at)::text || '-' || LPAD(public_id_seq::text, 5, '0')
    """)
    
    # Now make the column NOT NULL and add the server default for future inserts
    op.alter_column('complaints', 'public_id_seq', nullable=False, server_default=sa.text("nextval('complaint_public_seq')"))
    
    # Create the unique index
    op.create_index(op.f('ix_complaints_public_id_seq'), 'complaints', ['public_id_seq'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_public_id_seq'), table_name='complaints')
    op.drop_column('complaints', 'public_id_seq')
    
    # Drop the sequence
    op.execute("DROP SEQUENCE IF EXISTS complaint_public_seq")
    # ### end Alembic commands ###
