"""ai_grievance_intelligence

Revision ID: 73746b6761b7
Revises: 240c255c0a26
Create Date: 2026-08-16 16:08:32.444397

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73746b6761b7'
down_revision: Union[str, None] = '240c255c0a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_available_at'), 'analysis_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_complaint_id'), 'analysis_jobs', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_job_type'), 'analysis_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index('ix_analysis_jobs_status_available', 'analysis_jobs', ['status', 'available_at'], unique=False)
    op.add_column('complaint_analysis', sa.Column('duplicate_score', sa.Float(), nullable=True))
    op.add_column('complaint_analysis', sa.Column('spam_score', sa.Float(), nullable=True))
    op.add_column('complaint_analysis', sa.Column('candidate_issue_id', sa.UUID(), nullable=True))
    op.add_column('complaint_analysis', sa.Column('ai_status', sa.String(length=30), nullable=False, server_default='PENDING'))
    op.create_foreign_key(None, 'complaint_analysis', 'issue_clusters', ['candidate_issue_id'], ['id'])
    op.add_column('complaints', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_complaints_city_id'), 'complaints', ['city_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'cities', ['city_id'], ['id'])
    op.add_column('issue_clusters', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_issue_clusters_city_id'), 'issue_clusters', ['city_id'], unique=False)
    op.create_foreign_key(None, 'issue_clusters', 'cities', ['city_id'], ['id'])
    op.add_column('issue_complaints', sa.Column('relationship_type', sa.String(length=50), nullable=True))
    op.add_column('issue_complaints', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_column('users', 'city')
    op.drop_column('issue_complaints', 'confidence_score')
    op.drop_column('issue_complaints', 'relationship_type')
    op.drop_constraint(None, 'issue_clusters', type_='foreignkey')
    op.drop_index(op.f('ix_issue_clusters_city_id'), table_name='issue_clusters')
    op.drop_column('issue_clusters', 'city_id')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_city_id'), table_name='complaints')
    op.drop_column('complaints', 'city_id')
    op.drop_constraint(None, 'complaint_analysis', type_='foreignkey')
    op.drop_column('complaint_analysis', 'ai_status')
    op.drop_column('complaint_analysis', 'candidate_issue_id')
    op.drop_column('complaint_analysis', 'spam_score')
    op.drop_column('complaint_analysis', 'duplicate_score')
    op.drop_index('ix_analysis_jobs_status_available', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_job_type'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_complaint_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_available_at'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
