"""add password and ward to users

Revision ID: 754d4a098e0d
Revises: e649882f9739
Create Date: 2026-08-13 17:46:50.076950

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754d4a098e0d'
down_revision: Union[str, None] = 'e649882f9739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('ward', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ward')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
