"""Add designation to user

Revision ID: 9284456fe81d
Revises: 32037d992ba0
Create Date: 2026-08-18 18:31:21.275727

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9284456fe81d'
down_revision: Union[str, None] = '32037d992ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contractors', 'public_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.5'))
    op.alter_column('contractors', 'ai_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.8'))
    op.alter_column('contractors', 'officer_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.6'))
    op.alter_column('contractors', 'total_reviews_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('24'))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'designation')
    op.alter_column('contractors', 'total_reviews_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('24'))
    op.alter_column('contractors', 'officer_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.6'))
    op.alter_column('contractors', 'ai_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.8'))
    op.alter_column('contractors', 'public_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.5'))
    # ### end Alembic commands ###
